### ISSUE TITLE
Incompatible with recent API changes to slackclient.

### ISSUE THREAD

**Issue by bryannolen** [IRATEAU/sam-bot#12]
You could lock to version 1.3.2 in the requirements file, but would be better to upgrade to 2.x of the client API.

**Comment by colin-stubbs** [comment]
Have thrown a quick pull request in to fix in short term.

**Comment by 00willo** [comment]
This should probably be closed at #14 resolved this old incompatibility issue.

**Comment by ScottyAU** [comment]
Closing based on @00willo comment above.
