### ISSUE TITLE
Connection Failed - No traceback printed

### ISSUE THREAD

**Issue by Glhenn** [IRATEAU/sam-bot#9]
Once the SAMbot establishes the MISP connection, it fails immediately  - with no trackback or error data at all.. The only helpful data I can get is the verbose python output.

2018-12-04 11:03:32,931 - SAMbot - INFO - Connected to misp server successfully
# trying /usr/lib/python3.6/encodings/charmap.cpython-36m-x86_64-linux-gnu.so
# trying /usr/lib/python3.6/encodings/charmap.abi3.so
# trying /usr/lib/python3.6/encodings/charmap.so
# trying /usr/lib/python3.6/encodings/charmap.py
# /usr/lib/python3.6/encodings/__pycache__/charmap.cpython-36.pyc matches /usr/lib/python3.6/encodings/charmap.py
# code object from '/usr/lib/python3.6/encodings/__pycache__/charmap.cpython-36.pyc'
import 'encodings.charmap' # <_frozen_importlib_external.SourceFileLoader object at 0x7f1ac8a68208>
2018-12-04 11:03:33,222 - SAMbot - INFO - Connection failed. Exception traceback printed above.

Except for a bad encoding lib, I'm not sure what the issue could be.

**Comment by parker67** [comment]
This appears to be an issue connecting with Slack. 
`if slack_client.rtm_connect(with_team_state=False):
   somecode.....
else:
    logging.info("Connection failed. Exception traceback printed above.")`

Can you try this simple bot and confirm it works for me?
https://www.fullstackpython.com/blog/build-first-slack-bot-python.html

**Comment by parker67** [comment]
No response for 3 weeks. closing issue
